version: "3.8"

services:
  book-api:
    image: ${DOCKER_REGISTRY-}bookapi
    build:
      context: .
      dockerfile: Book-Api/Dockerfile
    ports:
        - "5000:5001"
    depends_on:
        - rabbitmq
        - redis 
   
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  
      - "15672:15672"  

  redis:
    image: redis
    ports:
      - "6379:6379"  # Redis port
       
        
