apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
      - name: book-api
        image: book-api

---
apiVersion: v1
kind: Service
metadata:
  name: bookapi-np-service
spec:
  type: NodePort
  selector:
    app: book-api
  ports:
  - name: book-api
    protocol: TCP
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: bookapi-clusterip
spec:
  type: ClusterIP
  selector:
    app: book-api
  ports:
  - name: book-api
    protocol: TCP
    port: 5000
    targetPort: 5000

