apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - name: redis-service
        image: redis
        ports:
          - containerPort: 6379
            name: redisservice

---
apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip
spec:
  type: ClusterIP
  selector:
    app: redis-service
  ports:
  - name: redisservice
    protocol: TCP
    port: 6379 
    targetPort: 6379

